
import pygame

# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
CAPTION = "Air Plane War"

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

# Player
PLAYER_SPEED = 5
PLAYER_LIVES = 3
PLAYER_SIZE = 40
PLAYER_COLOR = GREEN
PLAYER_START_POS = (SCREEN_WIDTH // 2, SCREEN_HEIGHT - 50)
PLAYER_SPECIAL_MAX = 100
PLAYER_SPECIAL_HIT_GAIN = 10
PLAYER_SPECIAL_KILL_GAIN = 25

# Boss
BOSS_SPEED = 3
BOSS_MAX_HP = 100
BOSS_SIZE = 60
BOSS_COLOR = RED
BOSS_START_POS = (SCREEN_WIDTH // 2, 50)

# Enemies
ENEMY_SPEED = 2
ENEMY_SIZE = 30
ENEMY_COLOR = BLUE
ENEMY_WAVES = 3
ENEMY_PER_WAVE = 3
ENEMY_MAX_ON_SCREEN = 3
ENEMY_SPAWN_INTERVAL = 700
ENEMY_SHOOT_DELAY = 900
ENEMY_BULLET_SPEED = 4
ENEMY_DIFFICULTY_GROWTH = 0.15
ENEMY_SHOT_LEVELS = {
    1: [0],
    2: [-2, 2],
    3: [-3, 0, 3],
    4: [-3, -1, 1, 3],
}

# Bullet
BULLET_SPEED = 7
BULLET_SIZE = 5
BULLET_COLOR_PLAYER = YELLOW
BULLET_COLOR_ENEMY = (255, 100, 100)

# Score
SCORE_ENEMY = 10
SCORE_BOSS_HIT = 2
SCORE_BOSS_KILL = 200
SHOT_LEVELS = [
    (0, [0]),
    (20, [-2, 2]),
    (50, [-3, 0, 3]),
    (80, [-4, -2, 0, 2, 4]),
]

# Actions
ACTION_LEFT = 0
ACTION_RIGHT = 1
ACTION_UP = 2
ACTION_DOWN = 3
ACTION_SHOOT = 4
ACTION_SPECIAL = 5

ACTIONS = [
    'LEFT',
    'RIGHT',
    'UP',
    'DOWN',
    'SHOOT',
    'SPECIAL'
]

NUM_ACTIONS = len(ACTIONS)
ENEMY_STATE_SIZE = 12
ENEMY_NUM_ACTIONS = NUM_ACTIONS

# Rewards
REWARD_HIT_PLAYER = 50
REWARD_PLAYER_LOSE_LIFE = 100
REWARD_GAME_OVER = 500
REWARD_BOSS_HIT = -30
REWARD_BOSS_DEATH = -200
REWARD_SURVIVAL = -0.1
REWARD_SHOOT_HIT = 10
REWARD_WASTE_BULLET = -2
REWARD_ENEMY_SURVIVAL = 0.05
REWARD_ENEMY_HIT = -20

# DQN Hyperparameters
STATE_SIZE = 16  # boss(2) + boss_hp(1) + player(2) + player_hp(1) + bullets(4*2=8 nearest) + time(1) + pattern(1)
HIDDEN_SIZE = 128
GAMMA = 0.99
EPSILON_START = 1.0
EPSILON_END = 0.01
EPSILON_DECAY = 0.995
LEARNING_RATE = 0.001
MEMORY_SIZE = 10000
BATCH_SIZE = 64
TARGET_UPDATE = 10
